name: MVP Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r envs/core.txt
    
    - name: Set environment variables for testing
      run: |
        echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
        echo "DEFAULT_SYMBOL=BTC/USDT" >> $GITHUB_ENV
        echo "TIMEFRAME=5m" >> $GITHUB_ENV
        echo "MAX_CAPITAL_PCT=0.05" >> $GITHUB_ENV
        echo "MODEL_NAME=test-model" >> $GITHUB_ENV
    
    - name: Run integration tests
      run: |
        pytest integration/tests/ -v --tb=short
    
    - name: Run latency measurement (smoke test)
      run: |
        python -m integration.scripts.measure_latency --cycles 3 --preview-fallback
    
    # - name: Freqtrade strategy smoke test
    #   run: |
    #     # Uncomment when freqtrade environment ready
    #     # python -c "from integration.strategy.AgentBridgeStrategy import AgentBridgeStrategy; print('Strategy import successful')" 